### PR TITLE
release 102 with support for ios 14.8

### PR DESCRIPTION
**Pull request by ahsan-a**
This is untested but should work. I updated everything based on [this commit](https://github.com/akemin-dayo/AppSync/commit/da82a9e1224ad266277eeeb998aa6faccd5c39f4).

### CODE REVIEW

**Comment by ahsan-a** [comment]
@Doregon I noticed you made issues where you verified that appsync works on the latest version of iOS. As I'm not in a situation where I can compile this ATM, would it be possible for you to clone this and test this out, or send me the deb if you can't test it?

**Comment by Mercandj** [comment]
Thank you all for your great work. Did you miss the bump of from `Version: 100.0` to `Version: 102.0` in the [control file line 10](https://github.com/akemin-dayo/AppSync/pull/83/files#diff-0fcd568a5cb9bdb4677b69354b11ee415af8f784519cff3da49a26f84eaee7f2) @ahsan-a?

Here the `.deb` you are asking for [net.angelxwind.appsyncunified_102.0_iphoneos-arm.deb.zip](https://github.com/akemin-dayo/AppSync/files/7191064/net.angelxwind.appsyncunified_102.0_iphoneos-arm.deb.zip)

I'm coming from Android dev so I'm very new into iOS jailbreak and I never tested this great tool before. The installation works well on 14.8 iPhoneX. Cannot confirm it's working as I'm not sure to what to expect 😅 (I'm just trying to have my own `.ipa` working more that 7days like Android `.apk` 😄)

Have a nice day 👋

**Comment by ahsan-a** [comment]
Thank you for spotting this, and for the build. It appears to be working perfectly. I've bumped the version in the control file, and I think this is ready to merge.

IMG_8222

**Comment by akemin-dayo** [comment]
Thanks for testing on iOS 14.8! ASU 102.0 will be going up soon.

**Comment by Mercandj** [comment]
Great, thank you a lot @akemin-dayo and @ahsan-a.
I confirm, working great, I can launch apps with "expired" certifs.

👏 

IMG_A20B2A7A0B41-1 2

**Pull request closed without merging**
