### PR TITLE
iOS 15: add SignerType

### LINKED ISSUE #131: could you support the Xina A15 iOS 15 jailbreak?
thx!!!!!

### PR DESCRIPTION
**Pull request by shatyuka**
See `-[MICodeSigningVerifier _getMICodeSignerTypeFromMISInfoDict:codeSignerType:profileType:error:]` in installd

May fix #131

### CODE REVIEW

**Comment by akemin-dayo** [comment]
Can confirm that the `SignerType` key is required for successful fakesigned app installation on iOS >= 15. Thanks for saving me the work of adding this myself! ;P

**Comment by wwpp3399** [comment]
I will test it tomorrow.

**Comment by wwpp3399** [comment]
I fixed for xina jailbreak, because it need arm64e arch.

**Comment by akemin-dayo** [comment]
That's not specific to the XinaA15 jailbreak — all arm64e processes require arm64e tweaks in order to modify their behaviour.

**Comment by akemin-dayo** [comment]
Sure, if you've found something to add!

**Comment by wwpp3399** [comment]
I just modified all makefiles to support arm64e and added signturetype in "ASU_MISValidateSignatureAndCopyInfo" func

**Comment by wwpp3399** [comment]
I am wrong,it is not 'signatruetype', it is 'SignerType',you have told it to me.

**Comment by akemin-dayo** [comment]
`SignerType` has already been added there in the latest commit, I just haven't yet released it on Cydia/APT.

https://github.com/akemin-dayo/AppSync/blob/master/AppSyncUnified-installd/AppSyncUnified-installd.x#L166

**Review by Rostomandj — COMMENTED** [review]
Ww

**Pull request merged**
